---
- name: Criando o diretorio APP
  file:
    state: directory
    path: '{{ item }}'
  with_items:
    - /opt/app
    - /opt/app/logs
    - /opt/app/conf
  register: criando_diretorios

- name: Copiando o Arquivo de deployment da app
  template:
    src: app-v1.yml.j2
    dest: /opt/app/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {src: 'service_app.yml', dest: '/opt/app/service_app.yml'}   
  register: copiando_service_file
  
- name: Executando o deploy da app
  shell: kubectl apply -f /opt/app/app-v1.yml
  register: deploy_app

- name: Criando o service da app
  shell: kubectl apply -f /opt/app/service_app.yml
  register: deploy_service_app
